[
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUS.TERM LOAN-CAP&INT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS CURRENT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS RESERVE ACCOUNT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS TERM LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CASH" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT ACCOUNT MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT DEPOSIT MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT DEPOSIT SER(HY)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT DEPOSIT SER(M)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT DEPOSIT SER(Q)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CORP CASH MANAGER PLUS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CORPORATE CASH MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "FIXED RATE BOND ANNUAL" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "FTSA SHELL 1" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "HOMEOWNER LOAN CAP&INT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "IS SHELL 1" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "IS SHELL 2" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY MANAGER 35 DAY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY MANAGER 95 DAY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY SELECT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY SELECT 35 DAY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY SELECT 95 DAY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "NATWEST SMALL BUSINESS L" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "OFFSET FLEXIBLE MORTGAGE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "OVERSEAS VOSTRO" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PERS.TERM LOAN-CAP&INT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PERSONAL BRIDGING" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PERSONAL LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PERSONAL TERM LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PROF PRACTICE LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "RELIEF & REAL" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SPECIAL INT BEARING" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STAFF LOAN (CAP&INT)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STEP" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-ATTACHED FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-CUSTOMER FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP INTEREST" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-INTERNAL FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-ITEMS IN COURSE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-FOREIGN CURRENCY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SWITCHED OUT ACCOUNT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SWITCHING OUT ACCOUNT" } }
]





[
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUS.TERM LOAN -CAP&INT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS CURRENT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS RESERVE ACCOUNT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS TERM LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "FIXED RATE BOND ANNUAL" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "FLEXIBLE LOAN-CAP&INT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "FLEXIBLE TERM LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "HOMEOWNER LOAN CAP&INT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "HOMEOWNER LOAN ENDOWMENT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LOAN RETURNED BUSINESS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LOAN RETURNED PERSONAL" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "NEW MORTGAGE PRODUCT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "OFFSET FLEXIBLE MORTGAGE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PERSONAL LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PROF PRACTICE LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "ROYAL BANK SMALL BUSINES" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STAFF LOAN (CAP&INT)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-ATTACHED FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-CUSTOMER FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSPINTEREST" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-INTERNAL FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-ITEMS IN COURSE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-FOREIGN CURRENCY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT ACCOUNT MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT DEPOSIT MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT DEPOSIT SER(HY)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT DEPOSIT SER(M)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT DEPOSIT SER(Q)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CORP CASH MANAGER PLUS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CORPORATE CASH MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "ECGD MEDIUM/LONG TERM" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "EDUCATION EXPENSES" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "ENDOWMENT HPL-SPECIAL" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "FTSA SHELL 1" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "GOLD CHEQUE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "GOLD DEPOSIT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "GOLD DEPOSIT (ANNUAL)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "HOUSE PURCHASE - QTLY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "HOUSE PURCHASE-MONTHLY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "INDIVIDUAL CLIENTS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "IS SHELL 1" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "IS SHELL 2" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "KEY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY MANAGER 35, DAY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY MANAGER 95 DAY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY SELECT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY SELECT 35 DAY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY SELECT 95 DAY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "OVERSEAS VOSTRO" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PERSONAL BRIDGING" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PRIVATE BANK" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PRIVATE BANKING CURRENT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "R21" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "RB CAM" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "RBIS INSURANCE BROKING" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "RBIS TRAVEL INSURANCE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "RELIEF & REAL" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "RELIEF & REAL INT BEAR" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "REVOLVING BUDGET" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "REVOLVING EQUITY RLSE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "ROUTE 15" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "ROYLINE DEPOSIT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SHIPBUILDING" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SHORT TERM EXPORT FIN." } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SPECIAL INT BEARING" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STAFF BUDGET" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STAFF HPL (CAP&INT)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STAFF HPL ENDOWMENT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STAFF HPL-BASE MAX 10%" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SWITCHED OUT ACCOUNT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SWITCHING OUT ACCOUNT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "TREASURERS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "VIRGIN ONE MIRAS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "VIRGIN ONE MT" } }
]



[
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "30 DAY BUSINESS RESERVE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "ADAPT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUS TERM LOAN CAP&INT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS CURRENT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS RESERVE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BUSINESS TERM LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "NON PERSONAL LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PERS TERM LOAN-CAP&INT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "PERSONAL LOAN" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SOLICITORS RESERVE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STAFF LOAN (CAP&INT)" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STUDENT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-ATTACHED FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-CUSTOMER FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-FOREIGN CURRENCY" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-INTERNAL FUNDS" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SUSP-ITEMS IN COURSE" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "BONUS ACCESS ACCOUNT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CASH" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CLIENT ACCOUNT MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "CRED CREDIT RESTRICTED." } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "DUAL" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "FTSA SHELL 1" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "IS SHELL 1" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "IS SHELL 2" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY MANAGER" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "LIQUIDITY SELECT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "RELIEF & REAL" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SPECIAL INT BEARING" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STAFF" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "STEP" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SWITCHED OUT ACCOUNT" } },
  { "initiatorDetailOutput.initiatorAccountType.accountType": { "equal": "SWITCHING OUT ACCOUNT" } }
]
